language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y texinfo; fi
  - ./scripts/install-xmake.sh
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make && ctest .
