language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
