/*
 * pixel.h
 * Author: wangwei.
 * Pixel operations, ported from great ffmpeg.
 */

#ifndef IMGUTIL_PIXEL_H
#define IMGUTIL_PIXEL_H

#include <stdint.h>
#include "../../libavutil/frame.h"

struct conv_context;
struct blend_context;

/* Create a blend context. */
struct blend_context *pixel_blend_get_context(void);

/* Fill blend specification by main image format. */
int pixel_blend_set_main(struct blend_context *ctx, enum AVPixelFormat fmt,
                         int width, int height);

/* Fill blend specification by overlay image format. */
int pixel_blend_set_overlay(struct blend_context *ctx, enum AVPixelFormat fmt,
                            int width, int height);

/* Do blend. */
int pixel_blend(struct blend_context *s,
                uint8_t *dst[8], int dst_linesize[8],
                const uint8_t *src[8], const int src_linesize[8],
                int x, int y);

/* Free blend context. */
void pixel_blend_free_context(struct blend_context **ctx);

/* Open up a new frame.
   Must use pixel_free_frm to free frame which generated by this API. */
AVFrame *pixel_alloc_frm(const uint32_t w, const uint32_t h,
                         enum AVPixelFormat fmt);

/* Free frame. */
void pixel_free_frm(AVFrame **src);

/* Create a convert context. */
struct conv_context *pixel_conv_get_context(void);

/* Fill convert format specification. */
int pixel_conv_set_dst_fmt(struct conv_context *ctx, enum AVPixelFormat fmt);

/* Fill convert size specification. */
int pixel_conv_set_dst_size(struct conv_context *ctx, uint32_t w, uint32_t h);

/* Convert format or size of frame data.
   Will alloc memory for the destination frame. */
AVFrame *pixel_conv_alloc(struct conv_context *ctx, const AVFrame *src);

/* Free conv context. */
void pixel_conv_free_context(struct conv_context **ctx);

/* Zoom picture. */
AVFrame *pixel_resize_frm(const AVFrame *src, uint32_t new_w, uint32_t new_h);

#endif //IMGUTIL_PIXEL_H